const REPORT_HEADER_PARTICULARS = "Parameter(s)";
const REPORT_HEADER_TEST_METHOD = "Test Method";
const REPORT_HEADER_SPECIFICATIONS = "Specifications";
const REPORT_HEADER_RESULTS = "Result";
const REPORT_HEADER_SNO = "S.NO";

module.exports = {
  REPORT_HEADER_PARTICULARS,
  REPORT_HEADER_TEST_METHOD,
  REPORT_HEADER_SPECIFICATIONS,
  REPORT_HEADER_RESULTS,
  REPORT_HEADER_SNO,
};
